# Write a program to check if a number is divisible by both 10 as well as 50. If it is divisible by 30
# as well, print “This number is divisible by 10, 50 and 30”. If not, print “This number divisible by 10 and 50 but not 30”. Use separate module for comparison and display the result.

string_input = input("Enter a string: ")
print("You entered:", string_input)

numeric_input = float(input("Enter a number: "))
print("You entered:", numeric_input)
